name: easy_localization_yaml
description: YAML loader for easy_localization package.
version: 0.1.0
repository: https://github.com/alexeyinkin/flutter-easy-localization-yaml

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  easy_localization: ^3.0.1
  flutter: { sdk: flutter }
  yaml: ^3.1.2

dev_dependencies:
  total_lints: ^3.1.1
